/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Jogo2048;



/**
 *
 * @author VICTOR
 */
public class Printar extends javax.swing.JFrame {
   
    Game matriz=new Game();
    public int[][] gameBoard=matriz.getGameBoard();
    int aux;
    
    

    //public Printar() {
    //}
    

    public Printar(/*int[][] gameBoard*/) {
        //this.gameBoard = gameBoard;
        initComponents();
    }
  
    
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("X");

        jLabel2.setText("X");

        jLabel3.setText("X");

        jLabel4.setText("X");

        jLabel5.setText("X");

        jLabel6.setText("X");

        jLabel7.setText("X");

        jLabel8.setText("X");

        jLabel9.setText("X");

        jLabel10.setText("X");

        jLabel11.setText("X");

        jLabel12.setText("X");

        jLabel13.setText("X");

        jLabel14.setText("X");

        jLabel15.setText("X");

        jLabel16.setText("X");

        jButton3.setText("v");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setText(">");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("^");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setText("<");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButton2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(jButton5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
      public void jButton3ActionPerformed(java.awt.event.ActionEvent evt) { 
          
        
        //for(int i=0;i<4;i++){
          
          
        //gameBoard=matriz.getGameBoard();
          gameBoard=matriz.getGameBoard();
        matriz.moveDown();
          matriz.printArray();
                       
        aux=gameBoard[0][0];
        jLabel1.setText(Integer.toString(aux));
        aux=gameBoard[0][1];
        jLabel2.setText(Integer.toString(aux));
        aux=gameBoard[0][2];
        jLabel3.setText(Integer.toString(aux));
        aux=gameBoard[0][3];
        jLabel4.setText(Integer.toString(aux));
        aux=gameBoard[1][0];
        jLabel5.setText(Integer.toString(aux));
        aux=gameBoard[1][1];
        jLabel6.setText(Integer.toString(aux));
        aux=gameBoard[1][2];
        jLabel7.setText(Integer.toString(aux));
        aux=gameBoard[1][3];
        jLabel8.setText(Integer.toString(aux));
        aux=gameBoard[2][0];
        jLabel9.setText(Integer.toString(aux));
        aux=gameBoard[2][1];
        jLabel10.setText(Integer.toString(aux));
        aux=gameBoard[2][2];
        jLabel11.setText(Integer.toString(aux));
        aux=gameBoard[2][3];
        jLabel12.setText(Integer.toString(aux));
        aux=gameBoard[3][0];
        jLabel13.setText(Integer.toString(aux));
        aux=gameBoard[3][1];
        jLabel14.setText(Integer.toString(aux));
        aux=gameBoard[3][2];
        jLabel15.setText(Integer.toString(aux));
        aux=gameBoard[3][3];
        jLabel16.setText(Integer.toString(aux));
        
        
        
       }
        
    public void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
            
       // gameBoard=matriz.getGameBoard();
        gameBoard=matriz.getGameBoard();
        matriz.moveRight();
        matriz.printArray();
        aux=gameBoard[0][0];
        jLabel1.setText(Integer.toString(aux));
        aux=gameBoard[0][1];
        jLabel2.setText(Integer.toString(aux));
        aux=gameBoard[0][2];
        jLabel3.setText(Integer.toString(aux));
        aux=gameBoard[0][3];
        jLabel4.setText(Integer.toString(aux));
        aux=gameBoard[1][0];
        jLabel5.setText(Integer.toString(aux));
        aux=gameBoard[1][1];
        jLabel6.setText(Integer.toString(aux));
        aux=gameBoard[1][2];
        jLabel7.setText(Integer.toString(aux));
        aux=gameBoard[1][3];
        jLabel8.setText(Integer.toString(aux));
        aux=gameBoard[2][0];
        jLabel9.setText(Integer.toString(aux));
        aux=gameBoard[2][1];
        jLabel10.setText(Integer.toString(aux));
        aux=gameBoard[2][2];
        jLabel11.setText(Integer.toString(aux));
        aux=gameBoard[2][3];
        jLabel12.setText(Integer.toString(aux));
        aux=gameBoard[3][0];
        jLabel13.setText(Integer.toString(aux));
        aux=gameBoard[3][1];
        jLabel14.setText(Integer.toString(aux));
        aux=gameBoard[3][2];
        jLabel15.setText(Integer.toString(aux));
        aux=gameBoard[3][3];
        jLabel16.setText(Integer.toString(aux));
        
       
    }                                        

    public void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
            
        //gameBoard=matriz.getGameBoard();
        matriz.moveUp();
        gameBoard=matriz.getGameBoard();
        matriz.printArray();
        aux=gameBoard[0][0];
        jLabel1.setText(Integer.toString(aux));
        aux=gameBoard[0][1];
        jLabel2.setText(Integer.toString(aux));
        aux=gameBoard[0][2];
        jLabel3.setText(Integer.toString(aux));
        aux=gameBoard[0][3];
        jLabel4.setText(Integer.toString(aux));
        aux=gameBoard[1][0];
        jLabel5.setText(Integer.toString(aux));
        aux=gameBoard[1][1];
        jLabel6.setText(Integer.toString(aux));
        aux=gameBoard[1][2];
        jLabel7.setText(Integer.toString(aux));
        aux=gameBoard[1][3];
        jLabel8.setText(Integer.toString(aux));
        aux=gameBoard[2][0];
        jLabel9.setText(Integer.toString(aux));
        aux=gameBoard[2][1];
        jLabel10.setText(Integer.toString(aux));
        aux=gameBoard[2][2];
        jLabel11.setText(Integer.toString(aux));
        aux=gameBoard[2][3];
        jLabel12.setText(Integer.toString(aux));
        aux=gameBoard[3][0];
        jLabel13.setText(Integer.toString(aux));
        aux=gameBoard[3][1];
        jLabel14.setText(Integer.toString(aux));
        aux=gameBoard[3][2];
        jLabel15.setText(Integer.toString(aux));
        aux=gameBoard[3][3];
        jLabel16.setText(Integer.toString(aux));
        
      
        
    }                                        

    public void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
            
        matriz.moveLeft();
        gameBoard=matriz.getGameBoard();
        matriz.printArray(); 
        aux=gameBoard[0][0];
        jLabel1.setText(Integer.toString(aux));
        aux=gameBoard[0][1];
        jLabel2.setText(Integer.toString(aux));
        aux=gameBoard[0][2];
        jLabel3.setText(Integer.toString(aux));
        aux=gameBoard[0][3];
        jLabel4.setText(Integer.toString(aux));
        aux=gameBoard[1][0];
        jLabel5.setText(Integer.toString(aux));
        aux=gameBoard[1][1];
        jLabel6.setText(Integer.toString(aux));
        aux=gameBoard[1][2];
        jLabel7.setText(Integer.toString(aux));
        aux=gameBoard[1][3];
        jLabel8.setText(Integer.toString(aux));
        aux=gameBoard[2][0];
        jLabel9.setText(Integer.toString(aux));
        aux=gameBoard[2][1];
        jLabel10.setText(Integer.toString(aux));
        aux=gameBoard[2][2];
        jLabel11.setText(Integer.toString(aux));
        aux=gameBoard[2][3];
        jLabel12.setText(Integer.toString(aux));
        aux=gameBoard[3][0];
        jLabel13.setText(Integer.toString(aux));
        aux=gameBoard[3][1];
        jLabel14.setText(Integer.toString(aux));
        aux=gameBoard[3][2];
        jLabel15.setText(Integer.toString(aux));
        aux=gameBoard[3][3];
        jLabel16.setText(Integer.toString(aux));
        
      
        
    }                                        
    /*
    
      }/*  
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
          //for(int i=0;i<4;i++){  
        aux=gameBoard[0][0];
        jLabel1.setText(Integer.toString(aux));
        aux=gameBoard[0][1];
        jLabel2.setText(Integer.toString(aux));
        aux=gameBoard[0][2];
        jLabel3.setText(Integer.toString(aux));
        aux=gameBoard[0][3];
        jLabel4.setText(Integer.toString(aux));
        aux=gameBoard[1][0];
        jLabel5.setText(Integer.toString(aux));
        aux=gameBoard[1][1];
        jLabel6.setText(Integer.toString(aux));
        aux=gameBoard[1][2];
        jLabel7.setText(Integer.toString(aux));
        aux=gameBoard[1][3];
        jLabel8.setText(Integer.toString(aux));
        aux=gameBoard[2][0];
        jLabel9.setText(Integer.toString(aux));
        aux=gameBoard[2][1];
        jLabel10.setText(Integer.toString(aux));
        aux=gameBoard[2][2];
        jLabel11.setText(Integer.toString(aux));
        aux=gameBoard[2][3];
        jLabel12.setText(Integer.toString(aux));
        aux=gameBoard[3][0];
        jLabel13.setText(Integer.toString(aux));
        aux=gameBoard[3][1];
        jLabel14.setText(Integer.toString(aux));
        aux=gameBoard[3][2];
        jLabel15.setText(Integer.toString(aux));
        aux=gameBoard[3][3];
        jLabel16.setText(Integer.toString(aux));
        
        //matriz.addNewNumbers();
        
        
          //}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add yur handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    /*
    public void imprimindo(){
        for(int i=0;i<3;i++){
        matriz.moveLeft();
        gameBoard=matriz.getGameBoard();
        //Printar.jButton3ActionPerformed();
        }
    }
*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Printar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Printar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Printar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Printar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Printar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables




}
